---
dirs:
  download: /tmp/tv3/d
  index: /tmp/tv3/censor
  publish: /Volumes/Verdura/Media/Video/Infantil
publish:
  Doraemon, el gat còsmic:
  Monster allergy:
  Una mà de contes:
  Els Dalton:
  El llibre de la selva:
  Bob, el manetes:
  Marsupilami:
  Rekkit, el conill màgic:
  L'hora del Timmy:
  Doraemon: Doraemon, el gat còsmic
  Ua man de condes: Una mà de contes
