---
:download_dir: /Volumes/Verdura/Media/In/super3/d
:index_dir: /Volumes/Verdura/Media/In/super3/censor
:publish_dir: /Volumes/Verdura/Media/Video/Infantil
:publish:
  Doraemon, el gat còsmic:
  Monster allergy:
  Una mà de contes:
  Els Dalton:
  El llibre de la selva:
  Bob, el manetes:
  Marsupilami:
  Rekkit, el conill màgic:
  L'hora del Timmy:
  Doraemon: Doraemon, el gat còsmic
  Ua man de condes: Una mà de contes
